# docker-compose.yml

services:
  frontend:
    build:
     context: ./
     dockerfile: Dockerfile
    container_name: frontend
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./:/app
      - /app/node_modules
